[[information-for-the-catalogue]]
== Information in the catalogue

We need to develop a shared vision for the content that the catalogue should hold and how it interlinks with other information products.

=== Scope for the catalogue and definition of “collection”

The scope for the catalogue needs to be defined. The core use case under consideration is the listing and description of collections holding preserved biological specimens, referred to here as "natural history collections". The consultation will focus on developing a solution that is robust and effective for natural history collections, but it is valuable to explore needs and opportunities around other types of natural science collection. Some of these may fit readily within the scope of the catalogue. In other cases, work on the catalogue may offer benefits to these other communities. Note in particular: 1) mant institutions hold both biological and geological collections and may manage these as a unified whole; 2) DiSSCo includes geological collections within its scope, and other networks such as iDigBio include at least paleontological collections; 3) GRSciColl was established to hold records on any scientific collection; and 4) the TDWG Collection Description standard is extensible for different collection types.

====
*Q10*. What is the definition for our purposes (minimal and sufficient criteria) of a natural history collection? How do collections relate to and differ from 1) institutions, 2) datasets and 3) collecting events (e.g. expeditions)? Should the following categories be included? Otherwise, are there important linkages or opportunities that should still be considered?

* Geological and paleontological collections
* Anthropological collections
* Ethnobotanical collections 
* Wood collections (xylaria)
* Tissue banks, DNA repositories and slide collections
* Living collections (microbial collections, zoos, aquaria, botanic gardens, seed banks)
* Personal collections
====

=== Identifiers for collections

Most collections are already identified by one or more collection codes and may have existing web identifiers (URLs, DOIs, etc.) in one or more databases. The catalogue may reuse one or other of these identifiers or may help to support a standardised scheme. GRSciColl exists to assist with standardisation of collection codes and machine-readable identifiers, but several other efforts are also in place. Unique identifiers for each collection will be important to maximise cross-linkage of information and standardise citation, but other existing identifiers should ideally resolve to the same information and be recognised as synonyms for the preferred identifiers.

====
*Q11*. What identifier schemes (IH collection codes, GRSciColl URIs, etc.) already exist and need to be maintained in some form? Do these schemes follow a consistent definition of a natural history collection? What characteristics of identifiers are important for use by machines and humans? Are there benefits in selecting any particular identifier scheme (e.g. https://www.doi.org/[DOIs] or https://ror.org/[ROR] identifiers)? What can be done to promote use of the preferred identifiers?
====

=== Hierarchical collection structures and subcollections

Within IH, each herbarium record usually corresponds to an institution with its own unique collection code, street address, etc. Within zoology, museums are often structured as a set of collections with differing and possibly hierarchical taxonomic scope. Specimens collected on famous expeditions or by significant researchers may have their own identity and appear as special collections. As a result, curators and researchers may wish to refer to different (potentially overlapping) sets of specimens as separate collections with their own names, identifiers and descriptions.

====
*Q12*. Should the catalogue support hierarchical relationships between collections (and collection records)? If so, how do parent-child relationships work, and do we infer information from parent to child or vice versa? 
====

=== Description of a collection

The https://www.tdwg.org/community/cd/[TDWG Collection Descriptions (CD) Interest Group] is currently developing the https://github.com/tdwg/cd[CD standard for collection descriptions] (evolving from the earlier TDWG Natural Collections Description (NCD) standard). Existing networks and institutional schemes use a variety of different formats or variants of metadata standards for their collection records, as a result of which interoperability between these resources is limited. To overcome this barrier, clarity is needed around factors such as preferred standards and vocabularies, mandatory fields and compatibility between information in different formats.

====
*Q13*. What descriptive information should be considered mandatory or desirable for each Collection? Does the TDWG CD work supply everything needed? Otherwise, what enhancements are necessary? How much of this information needs to be normalised for machine processing (rather than just for human readers)?
====

=== Wider data linkages
Information in the collection catalogue may be linked to a wide range of other biodiversity information (specimens, sequences, datasets, images, publications, etc.) to support information access and exploration.

====
*Q14*. What information should be linked to collection records? We should focus on making linkages that will actually justify the costs of creating and maintaining them. The following are likely to be candidates, but others are possible. In each case, we should determine whether the linkage needs to be bidirectional:

* Specimens held by a collection
* Type specimens held by a collection
* Species/taxa represented in a collection (with/without specimen counts)
* Sequences, images and other preparations from the collection (but these may be better treated as information about specimens rather than about the collection)
* Datasets (checklists, occurrences, sampling events) associated with the collection
* Collecting expeditions carried out by or contributing to the collection (modeled as sampling events?)
* Collectors associated with a collection
* Publications based on materials from the collection
* Researchers/staff associated with the collection
* Field notebooks
====

=== Information services relating to collections

The main value from the collection catalogue may appear in the information services that can be offered around the information managed. Considering these services may help to clarify the content requirements.

====
*Q15*. What do we want to do with the catalogue, beyond having clean and comprehensive linked open data about each collection? The following potential services are likely to be candidates, but others are possible. In each case, would the service depend on a partnership with other digital repositories (e.g. https://www.biodiversitylibrary.org/[BHL], https://www.gbif.org/[GBIF], http://www.catalogueoflife.org/[CoL])?

* Assess the growth, scale and value of the world's collections
* Discover the location of biological materials or the likely presence of biological materials for any taxon
* Develop discovery services for accessing information on type specimens or communicating with the relevant collection where the specimen is not digitised
* Identify sections of collections that should be digitised to answer specific questions
* Match gap analysis of published specimen data against the collection catalogue to prioritise digitisation for filling taxonomic, geographic, or other gaps.
* Discover holdings that make a particular collection unique, and therefore of even higher value
* Develop and fund collaborative digitisation programmes focused on understanding of the holdings of the network as a whole
* Develop cross-institutional loan systems and taxonomic workbenches
* Develop citation models for collections and track their impact
* Perform risk assessment of the health or stability of a collection
====
